### ISSUE TITLE
[BUG] missing appdmg dependency

### ISSUE THREAD

**Issue by remyleone** [getezy/ezy#42]
**Describe the bug**

The `npm run make` command fails with a missing dependency.

**To Reproduce**

```
$ npm run make

> ezy@1.0.0-beta.14 make
> electron-forge make

✔ Checking your system
⠋ Loading configuration
✔ Loading configuration
✔ Resolving make targets
  › Making for the following targets: dmg
✔ Running package command
  ✔ Preparing to package application
  ✔ Running packaging hooks
    ✔ Running generateAssets hook
    ✔ Running prePackage hook
      ✔ [plugin-webpack] Preparing native dependencies
      ✔ [plugin-webpack] Building webpack bundles
  ✔ Packaging application
    ✔ Packaging for x64 on darwin [4s]
  ✔ Running postPackage hook
✔ Running preMake hook
❯ Making distributables
  ✖ Making a dmg distributable for darwin/x64
    › Cannot find module 'appdmg'
      Require stack:
      - /Users/sieben/workspace/upstream/ezy/node_modules/electron-installer-dmg/src/index.js
      - /Users/sieben/workspace/upstream/ezy/node_modules/@electron-forge/maker-dmg/dist/MakerDMG.js
      - /Users/sieben/workspace/upstream/ezy/node_modules/@electron-forge/core/dist/util/require-search.js
      - /Users/sieben/workspace/upstream/ezy/node_modules/@electron-forge/core/dist/util/plugin-interface.js
      - /Users/sieben/workspace/upstream/ezy/node_modules/@electron-forge/core/dist/util/forge-config.js
      - /Users/sieben/workspace/upstream/ezy/node_modules/@electron-forge/core/dist/util/index.js
      - /Users/sieben/workspace/upstream/ezy/node_modules/@electron-forge/core/dist/api/index.js
      - /Users/sieben/workspace/upstream/ezy/node_modules/@electron-forge/cli/dist/electron-forge-make.js
◼ Running postMake hook

An unhandled rejection has occurred inside Forge:
Error: Cannot find module 'appdmg'
Require stack:
- /Users/sieben/workspace/upstream/ezy/node_modules/electron-installer-dmg/src/index.js
- /Users/sieben/workspace/upstream/ezy/node_modules/@electron-forge/maker-dmg/dist/MakerDMG.js
- /Users/sieben/workspace/upstream/ezy/node_modules/@electron-forge/core/dist/util/require-search.js
- /Users/sieben/workspace/upstream/ezy/node_modules/@electron-forge/core/dist/util/plugin-interface.js
- /Users/sieben/workspace/upstream/ezy/node_modules/@electron-forge/core/dist/util/forge-config.js
- /Users/sieben/workspace/upstream/ezy/node_modules/@electron-forge/core/dist/util/index.js
- /Users/sieben/workspace/upstream/ezy/node_modules/@electron-forge/core/dist/api/index.js
- /Users/sieben/workspace/upstream/ezy/node_modules/@electron-forge/cli/dist/electron-forge-make.js
at Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Module._load (node:internal/modules/cjs/loader:885:27)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at build (/Users/sieben/workspace/upstream/ezy/node_modules/electron-installer-dmg/src/index.js:9:18)
    at module.exports (/Users/sieben/workspace/upstream/ezy/node_modules/electron-installer-dmg/src/index.js:122:10)
    at async MakerDMG.make (/Users/sieben/workspace/upstream/ezy/node_modules/@electron-forge/maker-dmg/dist/MakerDMG.js:31:22)
    at async Task.task (/Users/sieben/workspace/upstream/ezy/node_modules/@electron-forge/core/dist/api/make.js:197:55)
    at async Task.run (/Users/sieben/workspace/upstream/ezy/node_modules/listr2/dist/index.cjs:978:11)
    at async /Users/sieben/workspace/upstream/ezy/node_modules/listr2/node_modules/p-map/index.js:57:22
```

**Expected behavior**

I expect ezy to build.

**Environment**
 - OS: macOS 13.1
 - ezy master branch

**Additional context**

**Comment by notmedia** [comment]
@remyleone Hi! Thank you for opening this issue!
How did you install project dependencies?
Try to remove them `rm -rf node_modules`, install them again via `npm ci` and then run `npm run make`

Right now on my local machine I have different error in `make` while copying `cp -R /ezy/out/ezy-darwin-x64/ezy.app /Volumes/ezy/ezy.app`. Trying to find the solution and I will check the CI that it passing this step.
